### ISSUE TITLE
Problem in Windows

### ISSUE THREAD

**Issue by kmaustral** [moremeyou/Obsidian-Tag-Buddy#1]
I've been waiting for years to have a function like this in Obsidian. I tried it out on Windows, but cltr-click sought to create a page from the tag. Then I lost the functionality of the keyboard entirely. I can't see a way of customising this in the hotkeys.

**Comment by moremeyou** [comment]
You can pull the same release (0.3.0). The issue is fixed. Let me know otherwise.
D

**Comment by kmaustral** [comment]
It still doesn't seem working for me. ctrl+click a tag brings up tag search instead. I'm using 0.3.0
![image](https://github.com/moremeyou/Obsidian-Tag-Buddy/assets/73867063/ad765a98-aab9-46fb-86aa-f37303f035a4)

**Comment by moremeyou** [comment]
Interesting. That issue looks to be from the Day Planner plugin. Was there
another error from Tag Buddy?

For now, I just installed Day Planner and tested on mac and window
versions. I added tags to the planner at different times and then clicked
with no issue. When clicking on them in the planner, you'll go to the note
for that plan. Then you can edit the tag. By default ctrl+click should do
the native tag search. But if you prefer it the other way around, there are
settings to toggle this so ctrl+click edits tags instead (and regular click
does native search).

But I'd like to clarify that tags are editable in reading mode in active
notes, embeds/blocks and tag summaries. Editing them in other complex views
can get risky because it has to figure out where that tag is in the source
file relative to where it is in other view types. I'm checking these other
views case-by-case.

Can you maybe try with some tags in regular notes? I'm not seeing any
errors on my end, but that doesn't mean they aren't happening. Curious if
regular notes/embeds/summaries are also give you an error.
David

**Comment by kmaustral** [comment]
I get the DayPlanner error regardless of what note I am on. There is no
error from Tag Buddy.

When I remove DayPlanner, I still get the same response: Ctrl+Click opens
tag search.

**Comment by moremeyou** [comment]
Okay, And when you click without ctrl?DavidOn Oct 6, 2023, at 02:39, kmaustral ***@***.***> wrote:﻿
I get the DayPlanner error regardless of what note I am on. There is no

error from Tag Buddy.



When I remove DayPlanner, I still get the same response: Ctrl+Click opens

tag search.

**Comment by kmaustral** [comment]
I was hoping that 0.6.8 would work for me, but I still get a tag search whenever I click a tag (with or without CTRL or ALT). I've tried this on a Sandbox site with no other plugins and it's the same issue.

**Comment by kmaustral** [comment]
And there are no messages on the console during these operations.
